BEGIN;

DROP TABLE IF EXISTS bot_permissions_cache CASCADE;
DROP TABLE IF EXISTS billing_subscriptions CASCADE;
DROP TABLE IF EXISTS group_events CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS group_settings CASCADE;
DROP TABLE IF EXISTS managed_groups CASCADE;
DROP TABLE IF EXISTS managed_bots CASCADE;
DROP TABLE IF EXISTS frg_transactions CASCADE;
DROP TABLE IF EXISTS frg_balances CASCADE;

COMMIT;
