/**
 * Master catalog of all 120 official upgradable Telegram Gifts
 * from https://api.changes.tg/gifts with real floor prices and supplies
 */

export interface OfficialGiftItem {
	name: string;
	slug: string;
	tag: string;
	floor: number;
	supply: number;
}

export const OFFICIAL_GIFTS_120: OfficialGiftItem[] = [
	{ name: 'Santa Hat', slug: 'santa_hat', tag: 'Seasonal', floor: 18.0, supply: 25000 },
	{ name: 'Signet Ring', slug: 'signet_ring', tag: 'Luxury', floor: 72.0, supply: 8000 },
	{ name: 'Precious Peach', slug: 'precious_peach', tag: 'Classic', floor: 65.0, supply: 6000 },
	{ name: 'Plush Pepe', slug: 'plush_pepe', tag: 'Bluechip', floor: 5400.0, supply: 5000 },
	{ name: 'Spiced Wine', slug: 'spiced_wine', tag: 'Seasonal', floor: 22.0, supply: 12000 },
	{ name: 'Jelly Bunny', slug: 'jelly_bunny', tag: 'Classic', floor: 18.0, supply: 15000 },
	{ name: "Durov's Cap", slug: 'durov_cap', tag: 'Bluechip', floor: 420.0, supply: 2500 },
	{ name: 'Perfume Bottle', slug: 'perfume_bottle', tag: 'Luxury', floor: 42.0, supply: 7500 },
	{ name: 'Eternal Rose', slug: 'eternal_rose', tag: 'Classic', floor: 32.0, supply: 9500 },
	{ name: 'Berry Box', slug: 'berry_box', tag: 'Seasonal', floor: 25.0, supply: 10000 },
	{ name: 'Vintage Cigar', slug: 'vintage_cigar', tag: 'Luxury', floor: 50.0, supply: 6000 },
	{ name: 'Magic Potion', slug: 'magic_potion', tag: 'Seasonal', floor: 40.0, supply: 6500 },
	{ name: 'Kissed Frog', slug: 'kissed_frog', tag: 'Classic', floor: 25.0, supply: 9000 },
	{ name: 'Hex Pot', slug: 'hex_pot', tag: 'Seasonal', floor: 35.0, supply: 8000 },
	{ name: 'Evil Eye', slug: 'evil_eye', tag: 'Talisman', floor: 36.0, supply: 7500 },
	{ name: 'Sharp Tongue', slug: 'sharp_tongue', tag: 'Classic', floor: 55.0, supply: 5500 },
	{ name: 'Trapped Heart', slug: 'trapped_heart', tag: 'Classic', floor: 48.0, supply: 7000 },
	{ name: 'Skull Flower', slug: 'skull_flower', tag: 'Seasonal', floor: 38.0, supply: 8500 },
	{ name: 'Scared Cat', slug: 'scared_cat', tag: 'Classic', floor: 48.0, supply: 10000 },
	{ name: 'Spy Agaric', slug: 'spy_agaric', tag: 'Seasonal', floor: 30.0, supply: 11000 },
	{ name: 'Homemade Cake', slug: 'homemade_cake', tag: 'Classic', floor: 20.0, supply: 14000 },
	{ name: 'Genie Lamp', slug: 'genie_lamp', tag: 'Talisman', floor: 85.0, supply: 4500 },
	{ name: 'Lunar Snake', slug: 'lunar_snake', tag: 'Seasonal', floor: 60.0, supply: 7000 },
	{ name: 'Party Sparkler', slug: 'party_sparkler', tag: 'Seasonal', floor: 15.0, supply: 20000 },
	{ name: 'Jester Hat', slug: 'jester_hat', tag: 'Classic', floor: 45.0, supply: 7500 },
	{ name: 'Witch Hat', slug: 'witch_hat', tag: 'Seasonal', floor: 32.0, supply: 9000 },
	{ name: 'Hanging Star', slug: 'hanging_star', tag: 'Classic', floor: 28.0, supply: 12000 },
	{ name: 'Love Candle', slug: 'love_candle', tag: 'Classic', floor: 22.0, supply: 15000 },
	{ name: 'Cookie Heart', slug: 'cookie_heart', tag: 'Seasonal', floor: 18.0, supply: 18000 },
	{ name: 'Desk Calendar', slug: 'desk_calendar', tag: 'Utility', floor: 38.0, supply: 10000 },
	{ name: 'Jingle Bells', slug: 'jingle_bells', tag: 'Seasonal', floor: 28.0, supply: 15000 },
	{ name: 'Snow Mittens', slug: 'snow_mittens', tag: 'Seasonal', floor: 16.0, supply: 22000 },
	{ name: 'Voodoo Doll', slug: 'voodoo_doll', tag: 'Talisman', floor: 55.0, supply: 6000 },
	{ name: 'Mad Pumpkin', slug: 'spooky_pumpkin', tag: 'Seasonal', floor: 32.0, supply: 8000 },
	{ name: 'Hypno Lollipop', slug: 'hypno_lollipop', tag: 'Classic', floor: 24.0, supply: 13000 },
	{ name: 'B-Day Candle', slug: 'bday_candle', tag: 'Classic', floor: 20.0, supply: 16000 },
	{ name: 'Bunny Muffin', slug: 'bunny_muffin', tag: 'Classic', floor: 19.0, supply: 15000 },
	{ name: 'Astral Shard', slug: 'astral_shard', tag: 'Talisman', floor: 75.0, supply: 5000 },
	{ name: 'Flying Broom', slug: 'flying_broom', tag: 'Seasonal', floor: 32.0, supply: 8000 },
	{ name: 'Crystal Ball', slug: 'crystal_ball', tag: 'Talisman', floor: 85.0, supply: 4500 },
	{ name: 'Eternal Candle', slug: 'eternal_candle', tag: 'Classic', floor: 26.0, supply: 12000 },
	{ name: 'Swiss Watch', slug: 'swiss_watch', tag: 'Luxury', floor: 160.0, supply: 3000 },
	{ name: 'Ginger Cookie', slug: 'gingerbread_man', tag: 'Seasonal', floor: 22.0, supply: 12500 },
	{ name: 'Mini Oscar', slug: 'mini_oscar', tag: 'Luxury', floor: 110.0, supply: 4000 },
	{ name: 'Lol Pop', slug: 'lol_pop', tag: 'Classic', floor: 18.0, supply: 18000 },
	{ name: 'Ion Gem', slug: 'ion_gem', tag: 'Talisman', floor: 95.0, supply: 4000 },
	{ name: 'Star Notepad', slug: 'star_notepad', tag: 'Utility', floor: 30.0, supply: 10000 },
	{ name: 'Loot Bag', slug: 'loot_bag', tag: 'Classic', floor: 65.0, supply: 6000 },
	{ name: 'Love Potion', slug: 'love_potion', tag: 'Seasonal', floor: 42.0, supply: 8000 },
	{ name: 'Toy Bear', slug: 'toy_bear', tag: 'Classic', floor: 28.0, supply: 12000 },
	{ name: 'Diamond Ring', slug: 'diamond_ring', tag: 'Luxury', floor: 110.0, supply: 4000 },
	{ name: 'Sakura Flower', slug: 'sakura_flower', tag: 'Seasonal', floor: 50.0, supply: 7000 },
	{ name: 'Sleigh Bell', slug: 'sleigh_bell', tag: 'Seasonal', floor: 25.0, supply: 14000 },
	{ name: 'Top Hat', slug: 'top_hat', tag: 'Luxury', floor: 65.0, supply: 5000 },
	{ name: 'Record Player', slug: 'record_player', tag: 'Luxury', floor: 130.0, supply: 3500 },
	{ name: 'Winter Wreath', slug: 'winter_wreath', tag: 'Seasonal', floor: 24.0, supply: 15000 },
	{ name: 'Snow Globe', slug: 'snow_globe', tag: 'Seasonal', floor: 38.0, supply: 8500 },
	{ name: 'Electric Skull', slug: 'golden_skull', tag: 'Talisman', floor: 230.0, supply: 1800 },
	{ name: 'Tama Gadget', slug: 'tama_gadget', tag: 'Tech', floor: 70.0, supply: 6000 },
	{ name: 'Candy Cane', slug: 'candy_cane', tag: 'Seasonal', floor: 15.0, supply: 25000 },
	{ name: 'Neko Helmet', slug: 'samurai_helmet', tag: 'Anime', floor: 170.0, supply: 2200 },
	{ name: 'Jack-in-the-Box', slug: 'jack_in_the_box', tag: 'Classic', floor: 35.0, supply: 9000 },
	{ name: 'Easter Egg', slug: 'easter_egg', tag: 'Seasonal', floor: 28.0, supply: 12000 },
	{ name: 'Bonded Ring', slug: 'bonded_ring', tag: 'Luxury', floor: 80.0, supply: 5500 },
	{ name: 'Pet Snake', slug: 'pet_snake', tag: 'Seasonal', floor: 45.0, supply: 8000 },
	{ name: 'Snake Box', slug: 'snake_box', tag: 'Seasonal', floor: 40.0, supply: 9000 },
	{ name: 'Xmas Stocking', slug: 'xmas_stocking', tag: 'Seasonal', floor: 18.0, supply: 20000 },
	{ name: 'Big Year', slug: 'big_year', tag: 'Seasonal', floor: 35.0, supply: 10000 },
	{ name: 'Holiday Drink', slug: 'holiday_drink', tag: 'Seasonal', floor: 20.0, supply: 16000 },
	{ name: 'Gem Signet', slug: 'gem_signet', tag: 'Luxury', floor: 90.0, supply: 4800 },
	{ name: 'Light Sword', slug: 'neon_sword', tag: 'Tech', floor: 180.0, supply: 2800 },
	{ name: 'Restless Jar', slug: 'restless_jar', tag: 'Talisman', floor: 50.0, supply: 7500 },
	{ name: 'Nail Bracelet', slug: 'nail_bracelet', tag: 'Luxury', floor: 75.0, supply: 6000 },
	{ name: 'Heroic Helmet', slug: 'space_helmet', tag: 'Tech', floor: 105.0, supply: 3800 },
	{ name: 'Bow Tie', slug: 'bow_tie', tag: 'Luxury', floor: 30.0, supply: 12000 },
	{ name: 'Heart Locket', slug: 'heart_locket', tag: 'Classic', floor: 45.0, supply: 8500 },
	{ name: 'Lush Bouquet', slug: 'lush_bouquet', tag: 'Seasonal', floor: 38.0, supply: 10000 },
	{ name: 'Whip Cupcake', slug: 'whip_cupcake', tag: 'Classic', floor: 22.0, supply: 15000 },
	{ name: 'Joyful Bundle', slug: 'joyful_bundle', tag: 'Seasonal', floor: 26.0, supply: 14000 },
	{ name: 'Cupid Charm', slug: 'cupid_charm', tag: 'Seasonal', floor: 55.0, supply: 6500 },
	{ name: 'Valentine Box', slug: 'valentine_box', tag: 'Seasonal', floor: 34.0, supply: 11000 },
	{ name: 'Snoop Dogg', slug: 'snoop_dogg', tag: 'Special', floor: 4.5, supply: 996000 },
	{ name: 'Swag Bag', slug: 'swag_bag', tag: 'Special', floor: 35.0, supply: 15000 },
	{ name: 'Snoop Cigar', slug: 'snoop_cigar', tag: 'Special', floor: 45.0, supply: 10000 },
	{ name: 'Low Rider', slug: 'low_rider', tag: 'Special', floor: 120.0, supply: 4000 },
	{ name: 'Westside Sign', slug: 'westside_sign', tag: 'Special', floor: 55.0, supply: 8000 },
	{ name: 'Stellar Rocket', slug: 'moon_rocket', tag: 'Tech', floor: 140.0, supply: 3200 },
	{ name: 'Jolly Chimp', slug: 'jolly_chimp', tag: 'Classic', floor: 40.0, supply: 9000 },
	{ name: 'Moon Pendant', slug: 'moon_pendant', tag: 'Talisman', floor: 68.0, supply: 6500 },
	{ name: 'Ionic Dryer', slug: 'ionic_dryer', tag: 'Utility', floor: 28.0, supply: 12000 },
	{ name: 'Input Key', slug: 'input_key', tag: 'Tech', floor: 85.0, supply: 5000 },
	{ name: 'Mighty Arm', slug: 'diamond_hands', tag: 'Crypto', floor: 125.0, supply: 4200 },
	{ name: 'Artisan Brick', slug: 'artisan_brick', tag: 'Utility', floor: 30.0, supply: 11000 },
	{ name: 'Clover Pin', slug: 'clover_pin', tag: 'Talisman', floor: 50.0, supply: 7500 },
	{ name: 'Sky Stilettos', slug: 'sky_stilettos', tag: 'Luxury', floor: 65.0, supply: 6000 },
	{ name: 'Fresh Socks', slug: 'fresh_socks', tag: 'Classic', floor: 14.0, supply: 30000 },
	{ name: 'Happy Brownie', slug: 'happy_brownie', tag: 'Classic', floor: 18.0, supply: 20000 },
	{ name: 'Ice Cream', slug: 'vice_cream', tag: 'Classic', floor: 30.0, supply: 15000 },
	{ name: 'Spring Basket', slug: 'spring_basket', tag: 'Seasonal', floor: 32.0, supply: 10000 },
	{ name: 'Instant Ramen', slug: 'instant_ramen', tag: 'Classic', floor: 22.0, supply: 18000 },
	{ name: 'Faith Amulet', slug: 'faith_amulet', tag: 'Talisman', floor: 70.0, supply: 5500 },
	{ name: 'Mousse Cake', slug: 'mousse_cake', tag: 'Classic', floor: 25.0, supply: 14000 },
	{ name: 'Bling Binky', slug: 'bling_binky', tag: 'Luxury', floor: 60.0, supply: 7000 },
	{ name: 'Money Pot', slug: 'golden_piggy', tag: 'Talisman', floor: 35.0, supply: 8800 },
	{ name: 'Pretty Posy', slug: 'pretty_posy', tag: 'Seasonal', floor: 26.0, supply: 15000 },
	{ name: "Khabib's Papakha", slug: 'khabib_papakha', tag: 'Special', floor: 350.0, supply: 3000 },
	{ name: 'UFC Strike', slug: 'ufc_strike', tag: 'Special', floor: 80.0, supply: 6000 },
	{ name: 'Victory Medal', slug: 'golden_trophy', tag: 'Special', floor: 195.0, supply: 2000 },
	{ name: 'Rare Bird', slug: 'rare_bird', tag: 'Classic', floor: 45.0, supply: 8000 },
	{ name: 'Mood Pack', slug: 'mood_pack', tag: 'Classic', floor: 28.0, supply: 12000 },
	{ name: 'Pool Float', slug: 'pool_float', tag: 'Seasonal', floor: 24.0, supply: 15000 },
	{ name: 'Timeless Book', slug: 'timeless_book', tag: 'Classic', floor: 44.0, supply: 12000 },
	{ name: 'Chill Flame', slug: 'chill_flame', tag: 'Talisman', floor: 52.0, supply: 10000 },
	{ name: 'Vice Cream', slug: 'vice_cream', tag: 'Classic', floor: 30.0, supply: 15000 },
	{ name: 'Surge Board', slug: 'surge_board', tag: 'Tech', floor: 78.0, supply: 7500 },
	{ name: 'Liberty Figure', slug: 'liberty_figure', tag: 'Special', floor: 115.0, supply: 5000 },
	{ name: "Durov's Glasses", slug: 'durov_glasses', tag: 'Bluechip', floor: 145.0, supply: 5000 },
	{ name: 'Fine Pen', slug: 'fine_pen', tag: 'Luxury', floor: 62.0, supply: 8000 },
	{ name: 'Intelligence Cup', slug: 'intelligence_cup', tag: 'Special', floor: 250.0, supply: 1500 },
	{ name: 'Algorithm Cup', slug: 'algorithm_cup', tag: 'Special', floor: 300.0, supply: 1200 },
];
